name: prodigiosovolcan

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks: 
      - node-network
    ports:
      - "9778:5173"
    environment:
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    # volumes:
    #   - ./frontend:/usr/src/app
    #   - /usr/src/app/node_modules
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend
          target: /usr/src/app
          action: sync

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks: 
      - node-network
    ports:
      - "5000:5000"
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - PORT=5000
    # volumes:
    #   - ./backend:/usr/src/app
    #   - /usr/src/app/node_modules
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend
          target: /usr/src/app
          action: sync

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certs/:/etc/nginx/certs/sso-app.in1t.dev:ro
    # restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - node-network

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./etc-letsencrypt:/etc/letsencrypt
  #     - ./var-lib-letsencrypt:/var/lib/letsencrypt
  #     - ./var-log-letsencrypt:/var/log/letsencrypt

networks:
  node-network:
    driver: bridge