name: prodigiosovolcan

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    networks: 
      - node-network
    ports:
      - "9778:5173"
    environment:
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend
          target: /usr/src/app
          action: sync

  backend:
    container_name: backend
    build:
      context: ./backend
    networks: 
      - node-network
    ports:
      - "5000:5000"
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PORT=5000
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend
          target: /usr/src/app
          action: sync

networks:
  node-network:
      driver: bridge
  default:
    name: prodigiosovolcan